dataSources:
- name: piperider_dbt
  type: bigquery
  dbt:
    profile: piperider_dbt
    target: prod
    projectDir: .

profiler:
   table:
     duplicateRows: true

telemetry:
  id: 09768aed64924da2bac4c30fb2862fee
