version: 2
models:
  - name: games_post_wide_day
    columns:
      - name: gameId
      - name: seasonId
      - name: seasonType
      - name: year
      - name: startTime
      - name: gameStatus
      - name: attendance
      - name: dayNight
        tests:
          - accepted_values:
              values: ['D']
      - name: duration
      - name: durationMinutes
      - name: awayTeamId
      - name: awayTeamName
      - name: homeTeamId
      - name: homeTeamName
      - name: venueId
      - name: venueName
      - name: venueSurface
      - name: venueCapacity
      - name: venueCity
      - name: venueState
      - name: venueZip
      - name: venueMarket
      - name: venueOutfieldDistances
      - name: homeFinalRuns
      - name: homeFinalHits
      - name: homeFinalErrors
      - name: awayFinalRuns
      - name: awayFinalHits
      - name: awayFinalErrors
      - name: homeFinalRunsForInning
      - name: awayFinalRunsForInning
      - name: inningNumber
      - name: inningHalf
      - name: inningEventType
      - name: inningHalfEventSequenceNumber
      - name: description
      - name: atBatEventType
      - name: atBatEventSequenceNumber
      - name: createdAt
      - name: updatedAt
      - name: status
      - name: outcomeId
      - name: outcomeDescription
      - name: hitterId
      - name: hitterLastName
      - name: hitterFirstName
      - name: hitterWeight
      - name: hitterHeight
      - name: hitterBatHand
      - name: pitcherId
      - name: pitcherFirstName
      - name: pitcherLastName
      - name: pitcherThrowHand
      - name: pitchType
      - name: pitchTypeDescription
      - name: pitchSpeed
      - name: pitchZone
      - name: pitcherPitchCount
      - name: hitterPitchCount
      - name: hitLocation
      - name: hitType
      - name: startingBalls
      - name: startingStrikes
      - name: startingOuts
      - name: balls
      - name: strikes
      - name: outs
      - name: rob0_start
      - name: rob0_end
      - name: rob0_isOut
      - name: rob0_outcomeId
      - name: rob0_outcomeDescription
      - name: rob1_start
      - name: rob1_end
      - name: rob1_isOut
      - name: rob1_outcomeId
      - name: rob1_outcomeDescription
      - name: rob2_start
      - name: rob2_end
      - name: rob2_isOut
      - name: rob2_outcomeId
      - name: rob2_outcomeDescription
      - name: rob3_start
      - name: rob3_end
      - name: rob3_isOut
      - name: rob3_outcomeId
      - name: rob3_outcomeDescription
      - name: is_ab
      - name: is_ab_over
      - name: is_hit
      - name: is_on_base
      - name: is_bunt
      - name: is_bunt_shown
      - name: is_double_play
      - name: is_triple_play
      - name: is_wild_pitch
      - name: is_passed_ball
      - name: homeCurrentTotalRuns
      - name: awayCurrentTotalRuns
      - name: awayFielder1
      - name: awayFielder2
      - name: awayFielder3
      - name: awayFielder4
      - name: awayFielder5
      - name: awayFielder6
      - name: awayFielder7
      - name: awayFielder8
      - name: awayFielder9
      - name: awayFielder10
      - name: awayFielder11
      - name: awayFielder12
      - name: awayBatter1
      - name: awayBatter2
      - name: awayBatter3
      - name: awayBatter4
      - name: awayBatter5
      - name: awayBatter6
      - name: awayBatter7
      - name: awayBatter8
      - name: awayBatter9
      - name: homeFielder1
      - name: homeFielder2
      - name: homeFielder3
      - name: homeFielder4
      - name: homeFielder5
      - name: homeFielder6
      - name: homeFielder7
      - name: homeFielder8
      - name: homeFielder9
      - name: homeFielder10
      - name: homeFielder11
      - name: homeFielder12
      - name: homeBatter1
      - name: homeBatter2
      - name: homeBatter3
      - name: homeBatter4
      - name: homeBatter5
      - name: homeBatter6
      - name: homeBatter7
      - name: homeBatter8
      - name: homeBatter9
      - name: lineupTeamId
      - name: lineupPlayerId
      - name: lineupPosition
      - name: lineupOrder
  - name: schedules_day
    columns:
      - name: gameId
      - name: gameNumber
      - name: seasonId
      - name: year
      - name: type
      - name: dayNight
        tests:
          - accepted_values:
              values: ['D']
      - name: duration
      - name: duration_minutes
      - name: homeTeamId
      - name: homeTeamName
      - name: awayTeamId
      - name: awayTeamName
      - name: startTime
      - name: attendance
      - name: status
      - name: created
