version: 2
models:
  - name: sample_games_post_wide
    columns:
      - name: gameId
        tests:
          - not_null
      - name: startTime
      - name: venueCapacity
      - name: dayNight
      - name: venueName
      - name: hitterLastName
      - name: hitterFirstName
      - name: homeFinalRuns
  - name: sample_schedules
    columns:
      - name: gameId
        tests:
          - not_null
      - name: startTime
      - name: homeTeamName
      - name: awayTeamName
      - name: status
      - name: dayNight
