version: 2

sources:
  - name: mlb
    description: ""
    tables:
      - name: games_post_wide
        description: ""
        columns:
          - name: gameid
            description: ""
          - name: seasonid
            description: ""
          - name: seasontype
            description: ""
          - name: year
            description: ""
          - name: starttime
            description: ""
          - name: gamestatus
            description: ""
          - name: attendance
            description: ""
          - name: daynight
            description: ""
          - name: duration
            description: ""
          - name: durationminutes
            description: ""
          - name: awayteamid
            description: ""
          - name: awayteamname
            description: ""
          - name: hometeamid
            description: ""
          - name: hometeamname
            description: ""
          - name: venueid
            description: ""
          - name: venuename
            description: ""
          - name: venuesurface
            description: ""
          - name: venuecapacity
            description: ""
          - name: venuecity
            description: ""
          - name: venuestate
            description: ""
          - name: venuezip
            description: ""
          - name: venuemarket
            description: ""
          - name: venueoutfielddistances
            description: ""
          - name: homefinalruns
            description: ""
          - name: homefinalhits
            description: ""
          - name: homefinalerrors
            description: ""
          - name: awayfinalruns
            description: ""
          - name: awayfinalhits
            description: ""
          - name: awayfinalerrors
            description: ""
          - name: homefinalrunsforinning
            description: ""
          - name: awayfinalrunsforinning
            description: ""
          - name: inningnumber
            description: ""
          - name: inninghalf
            description: ""
          - name: inningeventtype
            description: ""
          - name: inninghalfeventsequencenumber
            description: ""
          - name: description
            description: ""
          - name: atbateventtype
            description: ""
          - name: atbateventsequencenumber
            description: ""
          - name: createdat
            description: ""
          - name: updatedat
            description: ""
          - name: status
            description: ""
          - name: outcomeid
            description: ""
          - name: outcomedescription
            description: ""
          - name: hitterid
            description: ""
          - name: hitterlastname
            description: ""
          - name: hitterfirstname
            description: ""
          - name: hitterweight
            description: ""
          - name: hitterheight
            description: ""
          - name: hitterbathand
            description: ""
          - name: pitcherid
            description: ""
          - name: pitcherfirstname
            description: ""
          - name: pitcherlastname
            description: ""
          - name: pitcherthrowhand
            description: ""
          - name: pitchtype
            description: ""
          - name: pitchtypedescription
            description: ""
          - name: pitchspeed
            description: ""
          - name: pitchzone
            description: ""
          - name: pitcherpitchcount
            description: ""
          - name: hitterpitchcount
            description: ""
          - name: hitlocation
            description: ""
          - name: hittype
            description: ""
          - name: startingballs
            description: ""
          - name: startingstrikes
            description: ""
          - name: startingouts
            description: ""
          - name: balls
            description: ""
          - name: strikes
            description: ""
          - name: outs
            description: ""
          - name: rob0_start
            description: ""
          - name: rob0_end
            description: ""
          - name: rob0_isout
            description: ""
          - name: rob0_outcomeid
            description: ""
          - name: rob0_outcomedescription
            description: ""
          - name: rob1_start
            description: ""
          - name: rob1_end
            description: ""
          - name: rob1_isout
            description: ""
          - name: rob1_outcomeid
            description: ""
          - name: rob1_outcomedescription
            description: ""
          - name: rob2_start
            description: ""
          - name: rob2_end
            description: ""
          - name: rob2_isout
            description: ""
          - name: rob2_outcomeid
            description: ""
          - name: rob2_outcomedescription
            description: ""
          - name: rob3_start
            description: ""
          - name: rob3_end
            description: ""
          - name: rob3_isout
            description: ""
          - name: rob3_outcomeid
            description: ""
          - name: rob3_outcomedescription
            description: ""
          - name: is_ab
            description: ""
          - name: is_ab_over
            description: ""
          - name: is_hit
            description: ""
          - name: is_on_base
            description: ""
          - name: is_bunt
            description: ""
          - name: is_bunt_shown
            description: ""
          - name: is_double_play
            description: ""
          - name: is_triple_play
            description: ""
          - name: is_wild_pitch
            description: ""
          - name: is_passed_ball
            description: ""
          - name: homecurrenttotalruns
            description: ""
          - name: awaycurrenttotalruns
            description: ""
          - name: awayfielder1
            description: ""
          - name: awayfielder2
            description: ""
          - name: awayfielder3
            description: ""
          - name: awayfielder4
            description: ""
          - name: awayfielder5
            description: ""
          - name: awayfielder6
            description: ""
          - name: awayfielder7
            description: ""
          - name: awayfielder8
            description: ""
          - name: awayfielder9
            description: ""
          - name: awayfielder10
            description: ""
          - name: awayfielder11
            description: ""
          - name: awayfielder12
            description: ""
          - name: awaybatter1
            description: ""
          - name: awaybatter2
            description: ""
          - name: awaybatter3
            description: ""
          - name: awaybatter4
            description: ""
          - name: awaybatter5
            description: ""
          - name: awaybatter6
            description: ""
          - name: awaybatter7
            description: ""
          - name: awaybatter8
            description: ""
          - name: awaybatter9
            description: ""
          - name: homefielder1
            description: ""
          - name: homefielder2
            description: ""
          - name: homefielder3
            description: ""
          - name: homefielder4
            description: ""
          - name: homefielder5
            description: ""
          - name: homefielder6
            description: ""
          - name: homefielder7
            description: ""
          - name: homefielder8
            description: ""
          - name: homefielder9
            description: ""
          - name: homefielder10
            description: ""
          - name: homefielder11
            description: ""
          - name: homefielder12
            description: ""
          - name: homebatter1
            description: ""
          - name: homebatter2
            description: ""
          - name: homebatter3
            description: ""
          - name: homebatter4
            description: ""
          - name: homebatter5
            description: ""
          - name: homebatter6
            description: ""
          - name: homebatter7
            description: ""
          - name: homebatter8
            description: ""
          - name: homebatter9
            description: ""
          - name: lineupteamid
            description: ""
          - name: lineupplayerid
            description: ""
          - name: lineupposition
            description: ""
          - name: lineuporder
            description: ""

      - name: games_wide
        description: ""
        columns:
          - name: gameid
            description: ""
          - name: seasonid
            description: ""
          - name: seasontype
            description: ""
          - name: year
            description: ""
          - name: starttime
            description: ""
          - name: gamestatus
            description: ""
          - name: attendance
            description: ""
          - name: daynight
            description: ""
          - name: duration
            description: ""
          - name: durationminutes
            description: ""
          - name: awayteamid
            description: ""
          - name: awayteamname
            description: ""
          - name: hometeamid
            description: ""
          - name: hometeamname
            description: ""
          - name: venueid
            description: ""
          - name: venuename
            description: ""
          - name: venuesurface
            description: ""
          - name: venuecapacity
            description: ""
          - name: venuecity
            description: ""
          - name: venuestate
            description: ""
          - name: venuezip
            description: ""
          - name: venuemarket
            description: ""
          - name: venueoutfielddistances
            description: ""
          - name: homefinalruns
            description: ""
          - name: homefinalhits
            description: ""
          - name: homefinalerrors
            description: ""
          - name: awayfinalruns
            description: ""
          - name: awayfinalhits
            description: ""
          - name: awayfinalerrors
            description: ""
          - name: homefinalrunsforinning
            description: ""
          - name: awayfinalrunsforinning
            description: ""
          - name: inningnumber
            description: ""
          - name: inninghalf
            description: ""
          - name: inningeventtype
            description: ""
          - name: inninghalfeventsequencenumber
            description: ""
          - name: description
            description: ""
          - name: atbateventtype
            description: ""
          - name: atbateventsequencenumber
            description: ""
          - name: createdat
            description: ""
          - name: updatedat
            description: ""
          - name: status
            description: ""
          - name: outcomeid
            description: ""
          - name: outcomedescription
            description: ""
          - name: hitterid
            description: ""
          - name: hitterlastname
            description: ""
          - name: hitterfirstname
            description: ""
          - name: hitterweight
            description: ""
          - name: hitterheight
            description: ""
          - name: hitterbathand
            description: ""
          - name: pitcherid
            description: ""
          - name: pitcherfirstname
            description: ""
          - name: pitcherlastname
            description: ""
          - name: pitcherthrowhand
            description: ""
          - name: pitchtype
            description: ""
          - name: pitchtypedescription
            description: ""
          - name: pitchspeed
            description: ""
          - name: pitchzone
            description: ""
          - name: pitcherpitchcount
            description: ""
          - name: hitterpitchcount
            description: ""
          - name: hitlocation
            description: ""
          - name: hittype
            description: ""
          - name: startingballs
            description: ""
          - name: startingstrikes
            description: ""
          - name: startingouts
            description: ""
          - name: balls
            description: ""
          - name: strikes
            description: ""
          - name: outs
            description: ""
          - name: rob0_start
            description: ""
          - name: rob0_end
            description: ""
          - name: rob0_isout
            description: ""
          - name: rob0_outcomeid
            description: ""
          - name: rob0_outcomedescription
            description: ""
          - name: rob1_start
            description: ""
          - name: rob1_end
            description: ""
          - name: rob1_isout
            description: ""
          - name: rob1_outcomeid
            description: ""
          - name: rob1_outcomedescription
            description: ""
          - name: rob2_start
            description: ""
          - name: rob2_end
            description: ""
          - name: rob2_isout
            description: ""
          - name: rob2_outcomeid
            description: ""
          - name: rob2_outcomedescription
            description: ""
          - name: rob3_start
            description: ""
          - name: rob3_end
            description: ""
          - name: rob3_isout
            description: ""
          - name: rob3_outcomeid
            description: ""
          - name: rob3_outcomedescription
            description: ""
          - name: is_ab
            description: ""
          - name: is_ab_over
            description: ""
          - name: is_hit
            description: ""
          - name: is_on_base
            description: ""
          - name: is_bunt
            description: ""
          - name: is_bunt_shown
            description: ""
          - name: is_double_play
            description: ""
          - name: is_triple_play
            description: ""
          - name: is_wild_pitch
            description: ""
          - name: is_passed_ball
            description: ""
          - name: homecurrenttotalruns
            description: ""
          - name: awaycurrenttotalruns
            description: ""
          - name: awayfielder1
            description: ""
          - name: awayfielder2
            description: ""
          - name: awayfielder3
            description: ""
          - name: awayfielder4
            description: ""
          - name: awayfielder5
            description: ""
          - name: awayfielder6
            description: ""
          - name: awayfielder7
            description: ""
          - name: awayfielder8
            description: ""
          - name: awayfielder9
            description: ""
          - name: awayfielder10
            description: ""
          - name: awayfielder11
            description: ""
          - name: awayfielder12
            description: ""
          - name: awaybatter1
            description: ""
          - name: awaybatter2
            description: ""
          - name: awaybatter3
            description: ""
          - name: awaybatter4
            description: ""
          - name: awaybatter5
            description: ""
          - name: awaybatter6
            description: ""
          - name: awaybatter7
            description: ""
          - name: awaybatter8
            description: ""
          - name: awaybatter9
            description: ""
          - name: homefielder1
            description: ""
          - name: homefielder2
            description: ""
          - name: homefielder3
            description: ""
          - name: homefielder4
            description: ""
          - name: homefielder5
            description: ""
          - name: homefielder6
            description: ""
          - name: homefielder7
            description: ""
          - name: homefielder8
            description: ""
          - name: homefielder9
            description: ""
          - name: homefielder10
            description: ""
          - name: homefielder11
            description: ""
          - name: homefielder12
            description: ""
          - name: homebatter1
            description: ""
          - name: homebatter2
            description: ""
          - name: homebatter3
            description: ""
          - name: homebatter4
            description: ""
          - name: homebatter5
            description: ""
          - name: homebatter6
            description: ""
          - name: homebatter7
            description: ""
          - name: homebatter8
            description: ""
          - name: homebatter9
            description: ""
          - name: lineupteamid
            description: ""
          - name: lineupplayerid
            description: ""
          - name: lineupposition
            description: ""
          - name: lineuporder
            description: ""

      - name: schedules
        description: ""
        columns:
          - name: gameid
            description: ""
          - name: gamenumber
            description: ""
          - name: seasonid
            description: ""
          - name: year
            description: ""
          - name: type
            description: ""
          - name: daynight
            description: ""
          - name: duration
            description: ""
          - name: duration_minutes
            description: ""
          - name: hometeamid
            description: ""
          - name: hometeamname
            description: ""
          - name: awayteamid
            description: ""
          - name: awayteamname
            description: ""
          - name: starttime
            description: ""
          - name: attendance
            description: ""
          - name: status
            description: ""
          - name: created
            description: ""