dataSources:
- name: piperider_dbt
  type: bigquery
  dbt:
    profile: piperider_dbt
    target: dev
    projectDir: piperider_dbt

profiler:
   table:
     duplicateRows: true

telemetry:
  id: 021f1389167e4f8c87fb97122ae0b393
