name: piperider-ci

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  piperider-ci:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"

      # 「Google Workload identity federationでGitHub Actionsを設定してみた」 https://www.asobou.co.jp/blog/web/workload-identity
      - id: auth
        name: Authenticate to google cloud platform
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: install
        run: pip install -r requirements.txt

      - name: dbt run
        run: |
              cd piperider_dbt
              dbt --version
              dbt deps
              dbt build

      - name: PipeRider run
        run: |
              cd piperider_dbt
              piperider run

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'piperider_dbt/.piperider/outputs/latest/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1